# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

inhibit_all_warnings!

target 'SohuOpenSDKDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SohuOpenSDKDemo

  target 'SohuOpenSDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'TeaMediaPlayer',:path => '../'

end
